### PR TITLE
Fix: can not get the APISchema when registry is not version registry

### PR DESCRIPTION
**Pull request by zhaohuiweixiao**
### Summary
🐛🌐🚀

Fixed a bug in displaying UI data of addon packages in the web console. Changed `FindAddonPackagesDetailFromRegistry` to use `UIMetaOptions` instead of `CLIMetaOptions` in `pkg/addon/helper.go`.

> _`UIMetaOptions`_
> _Fix addon UI data bug_
> _Winter console glows_

### Walkthrough
* Fix UI data bug for addon packages by using `UIMetaOptions` instead of `CLIMetaOptions` in `FindAddonPackagesDetailFromRegistry` ([link](https://github.com/kubevela/kubevela/pull/6066/files?diff=unified&w=0#diff-c2cf26c57a54e0094a439c4c9f01e066d75f01eefc0264bfbcdc9d1524161d7cL257-R257))

FindAddonPackagesDetailFromRegistry can not get the APISchema data when registry is not version registry

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

1. add git type addon registry
2. enable fluxcd from this registry with local clusters
3. enable fluxcd from this registry without args

### Special notes for your reviewer

@wangyikewxgm

### CODE REVIEW

**Comment by Somefive** [comment]
Could you explain a bit more about why this change can fix the bug?

/cc @wangyikewxgm

**Comment by zhaohuiweixiao** [comment]
> Could you explain a bit more about why this change can fix the bug?
> 
> /cc @wangyikewxgm

the APISchema is only rendered if the GetParameter is true in the GetUIDataFromReader func.

image

**Comment by Somefive** [comment]
@zhaohuiweixiao Yes. But the function you are editing I think is used both in UI and CLI, is it right?

**Comment by zhaohuiweixiao** [comment]
> > Could you explain a bit more about why this change can fix the bug?
> > /cc @wangyikewxgm
> 
> the APISchema is only rendered if the GetParameter is true in the GetUIDataFromReader func.
> 
> image



> @zhaohuiweixiao Yes. But the function you are editing I think is used both in UI and CLI, is it right?

@Somefive Now, the GetUIDataFromReader only used in cli mode(vela addon status command). But it has bug in the cli mode.
when the registry is not a version registry(such as a git registry), the vela addon status -v command can't display the parameter of the addon.
image
Infact, it should dispaly all the fluxcd parameters:
image

**Review by wangyikewxgm — APPROVED** [review]
Good catch！

**Pull request merged**
