### PR TITLE
Feat(charts): add cert-manager support for "cluster-gateway" component in chart "vela-core"

### LINKED ISSUE #3847: [Feature] (charts) add cert-manager support for "cluster-gateway" tls certs and APIService
**Is your feature request related to a problem? Please describe.**

in chart "vela-core",component "admission-webhooks" has a support of cert-manager **but "cluster-gateway" not**.

**Describe the solution you'd like**

Add cert-manager support for component "cluster-gateway".

**Describe alternatives you've considered**

Noop

**Additional context**

Noop

### PR DESCRIPTION
**Pull request by cnfatal**
### Description of your changes

Fixes #3847 

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [x] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### Special notes for your reviewer

should review per commit to find out changes instead review the whole changes together.

### CODE REVIEW

**Comment by cnfatal** [comment]
Some check faild. 

```sh
installing kustomize-v3.8.2 into /root/go/bin
/root/go/bin/kustomize exists. Remove it first.
make: *** [makefiles/dependency.mk:64: kustomize] Error 1
Error: Process completed with exit code 2.
```
It cause by kustomize install script not this PR, please check it.

https://github.com/kubernetes-sigs/kustomize/blob/c3b5d8fa195ad70d75dd884379216b99184a7d56/hack/install_kustomize.sh#L78-L84

**Comment by Somefive** [comment]
Seems there are some problems with the helm chart install process. Did you verify the chart by `helm install kubevela ./chart/vela-core --wait --debug` and see if it can be correctly installed? If so, I will try to reproduce the installation problems later.

As for the kustomize issue, we are looking into it.

**Comment by Somefive** [comment]
BTW, thanks for the contributing! The modification generally looks good to me. Let's work out the CI.

**Comment by wonderflow** [comment]
> Some check faild.
> 
> ```shell
> installing kustomize-v3.8.2 into /root/go/bin
> /root/go/bin/kustomize exists. Remove it first.
> make: *** [makefiles/dependency.mk:64: kustomize] Error 1
> Error: Process completed with exit code 2.
> ```
> 
> It cause by kustomize install script not this PR, please check it.
> 
> https://github.com/kubernetes-sigs/kustomize/blob/c3b5d8fa195ad70d75dd884379216b99184a7d56/hack/install_kustomize.sh#L78-L84

I think it's caused by this PR https://github.com/kubevela/kubevela/pull/3846

Now it's merged, you could try rebase the master and the CI should be fixed.

**Review by wonderflow — APPROVED** [review]
thanks!

**Review by Somefive — APPROVED** [review]
Great Job!

**Pull request merged**
