### PR TITLE
Feat: support chart value to disable conversion on application crd

### PR DESCRIPTION
**Pull request by JarHMJ**
Signed-off-by: huangminjie <minjie.huang@daocloud.io>

support chart value to disable conversion on application crd （#3808）

### Description of your changes

Fixes #

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [x] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Review by wonderflow — COMMENTED** [review]
thanks for raising this, I'm thinking about drop the crd convertion by defaut with following reasons:

1. It has been more than 1 year since we migrate from v1alpha2 to v1beta1.
2. It adds a new docker image which may cause the installation slower, an also add more authorization on the ClusterRole.
3. It makes the chart a bit complex for maintain.

---

If we drop the conversion of CRD by default, it could be easier.
We just need to add the patch code in this `oamdev/kube-webhook-certgen` of the following section:

```
admissionWebhooks:
  enabled: true
  failurePolicy: Fail
  certificate:
    mountPath: /etc/k8s-webhook-certs
  patch:
    enabled: true
    image:
      repository: oamdev/kube-webhook-certgen
      tag: v2.3
      pullPolicy: IfNotPresent
```

1. We default value of `admissionWebhooks.patch.enabled` should be false. 
2. Remove the convertion in CRD.
3. when user enable this option, patch the convertion into CRD by the `kube-webhook-certgen` image. The code is here: https://github.com/oam-dev/kube-webhook-certgen

**Comment by JarHMJ** [comment]
I have commit a pr in `kube-webhook-certgen`
https://github.com/oam-dev/kube-webhook-certgen/pulls  
please review @wonderflow

**Comment by wonderflow** [comment]
@JarHMJ Great work, I've commented there. Please make sure this is well tested for real deploy, Thanks!

**Comment by JarHMJ** [comment]
> @JarHMJ Great work, I've commented there. Please make sure this is well tested for real deploy, Thanks!

yes, I test for kubevela v1.3.1 successfully. please help build a new image for `kube-webhook-certgen`

test step:
1. run `kubectl patch crd applications.core.oam.dev -p '{"spec":{"conversion":null}}'`
2. apply the following yaml
```
---
# Source: vela-core/templates/admission-webhooks/job-patch/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  kubevela-vela-core-admission
  namespace: vela-system
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: vela-core-admission
    helm.sh/chart: vela-core-1.3.1
    app.kubernetes.io/name: vela-core
    app.kubernetes.io/instance: kubevela
    app.kubernetes.io/version: "1.3.1"
    app.kubernetes.io/managed-by: Helm
---
# Source: vela-core/templates/admission-webhooks/job-patch/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name:  kubevela-vela-core-admission
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: vela-core-admission
    helm.sh/chart: vela-core-1.3.1
    app.kubernetes.io/name: vela-core
    app.kubernetes.io/instance: kubevela
    app.kubernetes.io/version: "1.3.1"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
    verbs:
      - get
      - update
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - update
---
# Source: vela-core/templates/admission-webhooks/job-patch/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  kubevela-vela-core-admission
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: vela-core-admission
    helm.sh/chart: vela-core-1.3.1
    app.kubernetes.io/name: vela-core
    app.kubernetes.io/instance: kubevela
    app.kubernetes.io/version: "1.3.1"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubevela-vela-core-admission
subjects:
  - kind: ServiceAccount
    name: kubevela-vela-core-admission
    namespace: vela-system
---
# Source: vela-core/templates/admission-webhooks/job-patch/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name:  kubevela-vela-core-admission
  namespace: vela-system
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: vela-core-admission
    helm.sh/chart: vela-core-1.3.1
    app.kubernetes.io/name: vela-core
    app.kubernetes.io/instance: kubevela
    app.kubernetes.io/version: "1.3.1"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
---
# Source: vela-core/templates/admission-webhooks/job-patch/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:  kubevela-vela-core-admission
  namespace: vela-system
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: vela-core-admission
    helm.sh/chart: vela-core-1.3.1
    app.kubernetes.io/name: vela-core
    app.kubernetes.io/instance: kubevela
    app.kubernetes.io/version: "1.3.1"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubevela-vela-core-admission
subjects:
  - kind: ServiceAccount
    name: kubevela-vela-core-admission
    namespace: vela-system
---
# Source: vela-core/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name:  kubevela-vela-core-admission-patch
  namespace: vela-system
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: vela-core-admission-patch
    helm.sh/chart: vela-core-1.3.1
    app.kubernetes.io/name: vela-core
    app.kubernetes.io/instance: kubevela
    app.kubernetes.io/version: "1.3.1"
    app.kubernetes.io/managed-by: Helm
spec:
  template:
    metadata:
      name:  kubevela-vela-core-admission-patch
      labels:
        app: vela-core-admission-patch
        helm.sh/chart: vela-core-1.3.1
        app.kubernetes.io/name: vela-core
        app.kubernetes.io/instance: kubevela
        app.kubernetes.io/version: "1.3.1"
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
        - name: patch
          image: 10.29.3.18/docker.io/oamdev/kube-webhook-certgen:v2.4
          imagePullPolicy: IfNotPresent
          args:
            - patch
            - --webhook-name=kubevela-vela-core-admission
            - --namespace=vela-system
            - --secret-name=kubevela-vela-core-admission
            - --patch-failure-policy=Fail
            - --crds={"name":"applications.core.oam.dev","conversion":{"strategy":"Webhook","webhook":{"clientConfig":{"service":{"name":"vela-core-webhook","namespace":"vela-system","path":"/convert","port":443}},"conversionReviewVersions":["v1beta1","v1alpha2"]}}}
      restartPolicy: OnFailure
      serviceAccountName: kubevela-vela-core-admission
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
---
```

**Comment by wonderflow** [comment]
Thanks @JarHMJ ！

I have merged your PR and build a release named v2.4.0 https://github.com/oam-dev/kube-webhook-certgen/tree/v2.4.0

It also contains a image build & push workflow. Could you help verify if it's worked by using the official image:  `oamdev/kube-webhook-certgen:v2.4.0` ?

Thanks very much!

**Comment by JarHMJ** [comment]
> Thanks @JarHMJ ！
> 
> I have merged your PR and build a release named v2.4.0 https://github.com/oam-dev/kube-webhook-certgen/tree/v2.4.0
> 
> It also contains a image build & push workflow. Could you help verify if it's worked by using the official image: `oamdev/kube-webhook-certgen:v2.4.0` ?
> 
> Thanks very much!

the official image: `oamdev/kube-webhook-certgen:v2.4.0` is worked in my cluster.

**Review by wonderflow — APPROVED** [review]
great work!

**Pull request merged**
