### PR TITLE
Feat: Add description column to vela trait and component command

### PR DESCRIPTION
**Pull request by hprotzek**
### Description of your changes
Using  the `description` field in the component and trait definition, show it now as an 3rd column in the vela cli command `vela components` and `vela traits`.

### CODE REVIEW

**Review by wonderflow — APPROVED** [review]

**Comment by wonderflow** [comment]
Please sign the dco

**Comment by hprotzek** [comment]
> Please sign the dco

done :-)

**Comment by wonderflow** [comment]
seems something was wrong with the CI, do you mind to make some other changes on commit message and force push again to trigger the CI?

**Comment by wonderflow** [comment]
ping @zzxwill @StevenLeiZhang @Somefive please review

**Review by zzxwill — APPROVED** [review]
Good job!

**Pull request merged**
