### PR TITLE
Feat: add message for `vela addon enable pyroscope`

### PR DESCRIPTION
**Pull request by fourierr**
Signed-off-by: Xiangbo Ma <maxiangboo@cmbchina.com>

### Description of your changes

Add message for `vela addon enable pyroscope`

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [x] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Review by wonderflow — CHANGES_REQUESTED** [review]
In this case, we will harccode for every add-on, that's a disaster

**Comment by fourierr** [comment]
> In this case, we will harccode for every add-on, that's a disaster

- I proposal that we need to add a field `message` in add-on's metadata.yaml, e.g
```yaml
name: pyroscope
version: 0.17.1
description: Pyroscope is an open source platform, consisting of server and agent. It allows the user to collect, store, and query the profiling data in a CPU and disk efficient way.
url: https://github.com/pyroscope-io/pyroscope
icon: https://raw.githubusercontent.com/pyroscope-io/pyroscope/main/webapp/images/favicon.ico

tags:
  - profiling tool

deployTo:
  control_plane: true

dependencies:
  - name: fluxcd

needNamespace:
  - pyroscope-system

invisible: false

meaaasge:
 - first-msg
 - second-msg
```
- Print the message when using `vela addon enbale xxx`.
@wonderflow

**Comment by wonderflow** [comment]
> I proposal that we need to add a field message in add-on's metadata.yaml.

Yes, we need something like this, can you propose a more detailed design? I think the message is not only fixed string, we will need some dynamically runtime variables here. \cc @wangyikewxgm

**Comment by fourierr** [comment]
What are the runtime variables? Can you give an example.

**Comment by wonderflow** [comment]
> What are the runtime variables? Can you give an example.

We should align with the helm chart Note.txt

**Comment by barnettZQG** [comment]
Let's add a 'note' field in the metadata file, and print it after the addon is installed.

**Comment by fourierr** [comment]
I will give a new feature request for detailed https://github.com/kubevela/kubevela/issues/4114

**Comment by Somefive** [comment]
Should be able to add customized message with NOTES.cue as mentioned https://kubevela.io/docs/platform-engineers/addon/addon-cue#notes-info-notescue .

Feel free to reopen it if it does not solve the issue.

**Pull request closed without merging**
