### PR TITLE
Fix: load local ComponentDefinitions recursively

### PR DESCRIPTION
**Pull request by TylerGillson**
### Description of your changes

Fixes issue where ComponentDefinitions are not loaded recursively from a definition directory when running `vela dry-run` in  `--offline` mode.

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [x] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

Prior to fix:
```bash
❯ vela dry-run -f ~/Downloads/app.yaml --offline -d vela-templates/definitions/internal
Error: failed to parseComponents: fetch component/policy type of nginx-demo: cannot load template "webservice" from cluster and provided ones: load template from component definition [webservice] : workloaddefinitions.core.oam.dev "webservice" not found
```
With the fix, all ComponentDefinitions under `vela-templates/definitions/internal/` are loaded properly and the Application resources are rendered successfully.

### Special notes for your reviewer
N/A

### CODE REVIEW

**Review by wonderflow — APPROVED** [review]
great job, would you like to add some test cases for this feature?

**Comment by TylerGillson** [comment]
@wonderflow sure, I've added a test case for the recursive definition loading scenario.

**Comment by TylerGillson** [comment]
@FogDong @wonderflow  - do you need me to add more negative test cases? Or is this ok?

**Comment by wonderflow** [comment]
the test is enough but it seems the unit test failed

**Review by FogDong — COMMENTED** [review]
```
Testing dry-run offline with deploy workflow step
```
This test failed.

**Review by StevenLeiZhang — APPROVED** [review]
LGTM

**Comment by TylerGillson** [comment]
My bad, @wonderflow, @FogDong... unit tests are fixed now.

**Pull request merged**
