### PR TITLE
Fix: remove observed generation

### PR DESCRIPTION
**Pull request by Somefive**
Signed-off-by: Somefive <yd219913@alibaba-inc.com>

### Description of your changes

Fixes #

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [x] Run `make reviewable` to ensure this PR is ready for review.

### CODE REVIEW

**Review by wonderflow — CHANGES_REQUESTED** [review]
Why remove

**Comment by Somefive** [comment]
> Why remove

Just for cleaning up. It is never used in our code now.

**Comment by Somefive** [comment]
Or should we keep it for observation?

**Comment by wonderflow** [comment]
> Or should we keep it for observation?

We need it, this field is a marker to tell other system who use vela Application object for integration that vela is reconciled ready for the `metadata.generation`.

**Pull request closed without merging**
