### PR TITLE
Feat: add delivery target crd

### PR DESCRIPTION
**Pull request by Somefive**
### Description of your changes

Add DeliveryTarget to describe the future EnvBinding placement.

### CODE REVIEW

**Comment by barnettZQG** [comment]
how to change the `envbinding` spec?

**Comment by Somefive** [comment]
> how to change the `envbinding` spec?

Currently I prefer not to change `envbinding` spec and make a glue code at apiserver temporarily.

**Comment by zzxwill** [comment]
Is there a usage example on this new CRD?

**Comment by Somefive** [comment]
> Is there a usage example on this new CRD?

Temporarily no. In my opinion, this feature is scheduled to be fully implemented some days later but APIServer seems requires the spec here.

**Comment by zzxwill** [comment]
> > Is there a usage example on this new CRD?
> 
> Temporarily no. In my opinion, this feature is scheduled to be fully implemented some days later but APIServer seems requires the spec here.

@barnettZQG Could you please describe the scenario of this new CRD in APIServer?

**Comment by barnettZQG** [comment]
> > how to change the `envbinding` spec?
> 
> Currently I prefer not to change `envbinding` spec and make a glue code at apiserver temporarily.

The `envbinding` needs to be associated with `DeliveryTarget`, otherwise, there is no point in defining the CRD now.

**Comment by Somefive** [comment]
> > > how to change the `envbinding` spec?
> > 
> > 
> > Currently I prefer not to change `envbinding` spec and make a glue code at apiserver temporarily.
> 
> The `envbinding` needs to be associated with `DeliveryTarget`, otherwise, there is no point in defining the CRD now.

When do you want this feature be fully implemented? This week?

**Review by wonderflow — CHANGES_REQUESTED** [review]
please hold until we discuss properly

**Pull request closed without merging**
