### PR TITLE
Fix: disable auto maxprocs logging

### PR DESCRIPTION
**Pull request by FogDong**
### Description of your changes

Fix https://github.com/kubevela/kubevela/issues/6503

copilot:all

Fixes #

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Comment by FogDong** [comment]
@wonderflow  Can you help to merge this?

**Review by wonderflow — APPROVED** [review]

**Comment by wonderflow** [comment]
It seems unit test is failing which blocks us merging it, can you help look into it? Thanks a lot

**Pull request merged**
