### PR TITLE
Feat: override array patch mode

### PR DESCRIPTION
**Pull request by zhiyu0729**
Signed-off-by: Zhiyu Wang <zhiyuwang.newbis@gmail.com>

### Description of your changes

A new override mode can support overriding list values
```
  components:
  - name: policy-test3
    properties:
      exposeType: ClusterIP
      image: nginx
      env:
        - name: key1
          value: value1
        - name: key2
          value: value2
        - name: key3
          value: value3
        - name: key4
          value: value4
        - name: key5
          value: value5
        - name: key6
          value: value6
        - name: key7
          value: value7
        - name: key8
          value: value8
        - name: key9
          value: value9
        - name: key10
          value: value10
    type: webservice
  policies:
  - name: prod
    properties:
      components:
      - name: policy-test3
        mode: overwrite
        properties:
          env:
            - null
            - null
            - null
            - null
            - null
            - null
            - null
            - null
            - nul
            - value: value998
    type: override
```
result
```
  containers:
    - name: policy-test3
      image: nginx
      env:
        - name: key1
          value: value1
        - name: key2
          value: value2
        - name: key3
          value: value3
        - name: key4
          value: value4
        - name: key5
          value: value5
        - name: key6
          value: value6
        - name: key7
          value: value7
        - name: key8
          value: value8
        - name: key9
          value: value9
        - name: key10
          value: value998
```

by this way, we can use `env[9].value=value998` in frontend, change special array list value.

if not overwrite
```
  components:
  - name: policy-test3
    properties:
      exposeType: ClusterIP
      image: nginx
      env:
        - name: key1
          value: value1
        - name: key2
          value: value2
        - name: key3
          value: value3
        - name: key4
          value: value4
        - name: key5
          value: value5
        - name: key6
          value: value6
        - name: key7
          value: value7
        - name: key8
          value: value8
        - name: key9
          value: value9
        - name: key10
          value: value10
    type: webservice
  policies:
  - name: prod
    properties:
      components:
      - name: policy-test3
        mode: overwrite
        properties:
          env:
            - name: key1
              value: value1
            - name: key2
              value: value2
            - name: key3
              value: value3
            - name: key4
              value: value4
            - name: key5
              value: value5
            - name: key6
              value: value6
            - name: key7
              value: value7
            - name: key8
              value: value8
            - name: key9
              value: value9
            - name: key10
              value: value998
    type: override
```

Fixes #

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Comment by zhiyu0729** [comment]
This is a rough implementation of our internals, I can continue work on it if this pr can be accpet.

**Review by Somefive — CHANGES_REQUESTED** [review]
The trait patch here follows the OAM model standard. The ArrayPatchMode here, although might provide more capability, increase the user's cost of understanding the override mechanism. BTW, the implementation of mergo library is swapped to a private implementation. The necessity of these changes are not convinced. I would suggest to raise an issue and make some discussion for it.

**Comment by zhiyu0729** [comment]
Change to upper layer implementation

**Comment by Somefive** [comment]
@zhiyu0729 Upper layer implementation? Your case is actually very useful. One of the suggestion is to add a env patch for your application, like 
```yaml
policies:
  - name: prod
    properties:
      components:
      - name: policy-test3
        traits:
        - type: env
          properties:
            key10: value998
    type: override
```
This should be much easier for you to modify only part of the environment variable.

**Pull request closed without merging**
