### PR TITLE
Fix: refactors http write resp to use 'html/template' instead

### PR DESCRIPTION
**Pull request by afzal442**
Signed-off-by: afzal442 <afzal442@gmail.com>

### Description of your changes

Fixes #

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Review by wonderflow — COMMENTED** [review]
Thanks for contributing, could you elaborate what's benefit from this refactors

**Comment by afzal442** [comment]
Thanks @wonderflow for reviewing this. 😄 
> could you elaborate what's benefit from this refactors

Sure, `http.ResponseWriter.write()` bypasses HTML escaping that prevents cross-site scripting vulnerabilities. Instead, if we use the 'html/template' package and render data using template.Execute(), it will produce safe, escaped HTML output.
Ref: https://pkg.go.dev/html/template

BTW you can verify locally like how it behaves. Thanks

**Review by wonderflow — APPROVED** [review]
thanks for explaning the benifit

**Review by wangyikewxgm — APPROVED** [review]
LGTM

**Review by Somefive — APPROVED** [review]

**Pull request merged**
