### PR TITLE
Fix(cli): try to get mapValue type name

### LINKED ISSUE #2208: vela show service-binding can't display information inside map
```
$ vela show service-binding
# Properties
+-------------+------------------------------------------------+------------------+----------+---------+
|    NAME     |                  DESCRIPTION                   |       TYPE       | REQUIRED | DEFAULT |
+-------------+------------------------------------------------+------------------+----------+---------+
| envMappings | The mapping of environment variables to secret | map[string]{...} | true     |         |
+-------------+------------------------------------------------+------------------+----------+---------+
```

The expected output is the type.

### PR DESCRIPTION
**Pull request by cuichenli**
### Description of your changes

<!--

Briefly describe what this pull request does. We love pull requests that resolve an open KubeVela issue. If yours does, you
can uncomment the below line to indicate which issue your PR fixes, for example
"Fixes #500":

-->

Fixes #2208. Try to get the mapValue type name from `Source`.

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

Ran the `vela show service-binding` locally, and the output is like this:
```
❯ ./bin/vela show service-binding                                                                                                                                                                                                                                        
# Properties
+-------------+------------------------------------------------+------------+----------+---------+
|    NAME     |                  DESCRIPTION                   |    TYPE    | REQUIRED | DEFAULT |
+-------------+------------------------------------------------+------------+----------+---------+
| envMappings | The mapping of environment variables to secret | #KeySecret | true     |         |
+-------------+------------------------------------------------+------------+----------+---------+
```
<!--
Before reviewers can be confident in the correctness of this pull request, it
needs to tested and shown to be correct. Briefly describe the testing that has
already been done or which is planned for this change.
-->


I am new to the kubevela project and may made a wrong assumption regarding the `type` (I am not sure if this type `name` is the correct information to display). Feel free to reject. Thanks
<!--

Be sure to direct your reviewers'
attention to anything that needs special consideration.

-->

### CODE REVIEW

**Comment by cuichenli** [comment]
hey @wonderflow, i have updated the code based on comment, please check again. thanks

**Comment by wonderflow** [comment]
@cuichenli Hi， sorry  for the late response, would you mind to rebase and fix the conflict, Thanks.

**Review by wonderflow — APPROVED** [review]
LGTM

**Comment by wonderflow** [comment]
@cuichenli please sign off the DCO

**Pull request merged**
