### PR TITLE
Feat: apply-component supports namespace

### PR DESCRIPTION
**Pull request by nuclearwu**
Signed-off-by: wuzhongjian wuzhongjian_yewu@cmss.chinamobile.com

### Description of your changes
1. Adding a namespace parameter in `apply-component.cue` and `builtin-apply-component.cue` to support setting namespace for `apply-component` step.
2.  if the namespace of the `apply-component` is not set, it will not be assigned a default value to the override namespace.

### Summary
🆕📝🚀

This pull request adds a new `namespace` parameter to the `apply-component` workflow step, which allows applying components and traits to different namespaces in the application definition. It also updates the generator, the Helm chart template, the CUE definition, and the documentation to support this feature.

> _`namespace` added_
> _to `apply-component` step_
> _autumn leaves scatter_

### Walkthrough
* Add a new parameter `namespace` to the `apply-component` workflow step definition, which allows users to specify the namespace where the component and traits will be applied. ([link](https://github.com/kubevela/kubevela/pull/6248/files?diff=unified&w=0#diff-d04ff4062f6d641448d51084a8340da502252bad348799cd4f8d89f5fdbbdfa7R22-R23), [link](https://github.com/kubevela/kubevela/pull/6248/files?diff=unified&w=0#diff-17fef7796b683f2995e4bd6650af842e7d1c0c116471d2f206ec405b5c192256R17-R18), [link](https://github.com/kubevela/kubevela/pull/6248/files?diff=unified&w=0#diff-b294236ceeaba10f0beef13117ca02e3063a2c33a6f7c67ae0f2195e865fa9e2L21-R23))
* Pass the `namespace` parameter to the `oam.#ApplyComponent` trait in the CUE template for the `apply` task, which will use it to apply the component and traits to the specified namespace. ([link](https://github.com/kubevela/kubevela/pull/6248/files?diff=unified&w=0#diff-b294236ceeaba10f0beef13117ca02e3063a2c33a6f7c67ae0f2195e865fa9e2L8-R10))
* Add a new field `Namespace` to the `StepProperties` struct in the Go code, which will store the value of the `namespace` parameter from the workflow step definition. ([link](https://github.com/kubevela/kubevela/pull/6248/files?diff=unified&w=0#diff-4170e9b730a11fdd789c7b33a0871e4a67c4e37910815cc262286ac8ec076212R255))
* Set a default value for the `Namespace` field in the `StepProperties` struct, which will use the same namespace as the application if the user does not specify the `namespace` parameter. ([link](https://github.com/kubevela/kubevela/pull/6248/files?diff=unified&w=0#diff-4170e9b730a11fdd789c7b33a0871e4a67c4e37910815cc262286ac8ec076212R264-R266))
* Modify the logic of converting the `StepProperties` struct to a raw extension for the workflow step, which will exclude the `namespace` parameter if the component type is `raw` or `k8s-objects`, and include it otherwise. ([link](https://github.com/kubevela/kubevela/pull/6248/files?diff=unified&w=0#diff-4170e9b730a11fdd789c7b33a0871e4a67c4e37910815cc262286ac8ec076212L290-R305))
* Modify the example usage of the `apply-component` workflow step in the documentation, which shows how to optionally specify the `namespace` parameter for the step. ([link](https://github.com/kubevela/kubevela/pull/6248/files?diff=unified&w=0#diff-9e546a8bf33fb0f29a44924f3621c3016273cc56d76682fd38be99e39f1bca1aL27-R28))

Fixes #

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Comment by nuclearwu** [comment]
ping @chivalryq

**Comment by wonderflow** [comment]
can you please check if this issue still exists after this PR merged: https://github.com/kubevela/kubevela/issues/6269

**Comment by nuclearwu** [comment]
> #6269



> can you please check if this issue still exists after this PR merged: #6269

I checked unit tests similar to it and found that it works well. I have revised the logic to ensure that if the namespace of the apply component is not set, it will not be assigned a value to the override namespace.

> can you please check if this issue still exists after this PR merged: #6269

@wonderflow I checked unit tests similar to it and  it works well. I have revised the logic to ensure that if the namespace of the apply component is not set, it will not be assigned a default value to the override namespace.
```
if o.Namespace != "" {
              stepProperties["namespace"] = o.Namespace
}
```

**Review by chivalryq — APPROVED** [review]
I checked the op.#ApplyComponent. Skipping setting namespace (`overrideNamespace` inside the op.#ApplyComponent logic) make sense to me. `overrideNamespace` will be empty and that's fine for the subsequent process.

Back to this change, I think it's even OK to set stepProperties["namespace"] to o.Namespace without empty guarder. Both case will result `overrideNamespace` is empty string.

`overrideNamespace` parsing: https://github.com/kubevela/kubevela/blob/94cbcad471c25f8b31809cd708b2686f7bc42de9/pkg/workflow/providers/oam/apply.go

**Review by FogDong — APPROVED** [review]

**Review by wonderflow — APPROVED** [review]

**Pull request merged**
