### PR TITLE
Fix: typo

### PR DESCRIPTION
**Pull request by susheelpal**
### Summary
:pencil2::memo::books:

Fix typos and grammar in `README.md`. Use "as per" instead of "per" for clarity.

> _`README.md` file_
> _Typos fixed, grammar improved_
> _As per autumn's breeze_

### Walkthrough
* Fix typos and improve grammar in `README.md` ([link](https://github.com/kubevela/kubevela/pull/6069/files?diff=unified&w=0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L41-R41),                             F0L68R

Fixes #

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [x] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Comment by Somefive** [comment]
Please fix the DCO by signing your commit. Thanks :)

**Comment by susheelpal** [comment]
@Somefive Thanks for your comment. I am new to this project and I don't know how to do that. could you please guide me?

**Comment by Somefive** [comment]
image

You can follow the instructions for the details of non-successful CI check "DCO".

**Comment by susheelpal** [comment]
Hello @Somefive, I actually edited in GitHub itself and committed. But, I did not get that when I cloned and tried to find my commit to edit.

**Review by chivalryq — APPROVED** [review]

**Pull request merged**
