### PR TITLE
Fix: context.namespace use the namespace from override policy

### PR DESCRIPTION
**Pull request by Somefive**
Signed-off-by: Somefive <yd219913@alibaba-inc.com>

### Description of your changes

context.namespace use override namespace when rendering component and trait

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Review by wonderflow — APPROVED** [review]

**Comment by fourierr** [comment]
I want to make sure it,  the defination of context.namespace in cue.context has changed from app's ns to pod's ns ? @wonderflow

**Comment by wonderflow** [comment]
@fourierr Not exactly, the context.namespace is the namespace of component, in this PR, it will align to component which is affected by the override policy.

**Comment by fourierr** [comment]
> @fourierr Not exactly, the context.namespace is the namespace of component, in this PR, it will align to component which is affected by the override policy.

you are right, but the `context.appNamespace` is useful to trait cr, trait cr has been created in app's ns for more convenient management.

**Comment by wonderflow** [comment]
@fourierr By default, the trait will be created in the app namespace, so it's not necessary to use `context.appNamespace`.

**Pull request merged**
