### PR TITLE
Feat: add feature of refreshing resource view and fix the bug of stucking

### LINKED ISSUE #4741: [Bug] Stuck occurs when switching resource views in `vela top`.
**Describe the bug**

Stuck occurs when switching resource views in `vela top`.

**To Reproduce**

**Expected behavior**

Refer to the [tview's concurrency principle](https://pkg.go.dev/github.com/rivo/tview#hdr-Concurrency), all UI change actions will execute in the main goroutine, so when the UI action need data rendering which needs long time network transmit, the stuck will happen.

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

### LINKED ISSUE #4742: [Feature] add the feature of refreshing resource view in `vela top`
**Is your feature request related to a problem? Please describe.**

Now the resource view won't refresh after rendering first. But state of resource will update, so we need add the refresh feature.

**Describe the solution you'd like**

Add the key action **R** related to the refresh action.

view refresh

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Hanmengnan**
### Description of your changes

1. Add the key action R related to the refresh action. Users can press the key **R** to refresh the resource view. And more the view will refresh auto in every 10 second.

view refresh

2. I separate view initialization and data loading. Data loading uses a separate goroutine, and then the UI is redrawn after loading. On the user side, it seems that the view switching is responsive in seconds, but the data will be refreshed later.

Fixes #4741 
Fixes #4742

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Review by wonderflow — COMMENTED** [review]
is it able to refresh automatically？

**Comment by Hanmengnan** [comment]
> is it able to refresh automatically？

Not yet, but I can add this feature.

**Comment by Hanmengnan** [comment]
> is it able to refresh automatically？

Already add the feature

**Comment by Somefive** [comment]
Is there any reason for use key **R**? I'm not sure what is the most common way to refresh. Is it more usual to use F5? Or is **R** the refresh key for k9s?

**Comment by Hanmengnan** [comment]
> Is there any reason for use key **R**? I'm not sure what is the most common way to refresh. Is it more usual to use F5? Or is **R** the refresh key for k9s?

Because the first letter of "Refresh" is "R", so I choose it. And the key in K9s is "Ctrl+R"

**Comment by Somefive** [comment]
> > Is there any reason for use key **R**? I'm not sure what is the most common way to refresh. Is it more usual to use F5? Or is **R** the refresh key for k9s?
> 
> Because the first letter of "Refresh" is "R", so I choose it. And the key in K9s is "Ctrl+R"

I see. I'm okay with **R** but it might need to be careful if we want to add keys like `return` in the future.

**Review by Somefive — APPROVED** [review]

**Pull request merged**
