### PR TITLE
Chore: tidy appHandler

### PR DESCRIPTION
**Pull request by chivalryq**
### Description of your changes

This PR mainly have several effects:
1. Depracate `PackagedWorkloadResources` and `PackagedTraitResources` field in ComponentManifest. They are for helm-based component which has been depracated in schematic of ComponentDefinition
2. Rename `StandardWorkload -> ComponentOutput` and `Traits -> ComponentOutputAndTraits`. The original names (StandardWorkload and Traits) can not reflect the actual usage of the fields.
  - `ComponentOutput` contains K8s resource generated from "output" block of ComponentDefinition
  - `ComponentOutputsAndTraits` contains both resources generated from "outputs" block of ComponentDefinition and resources generated from TraitDefinition
3. Remove some unreachable code after depracation.

### Summary
🚚🗑️🛠️

Refactored the appfile package and related packages to use a new data model for application components and their outputs. Renamed some structs and fields to align with the OAM spec and improve clarity. Simplified the application revision logic to use component manifests directly. Updated the tests and CLI commands to reflect the changes.

> _Sing, O Muse, of the mighty refactor that reshaped the appfile_
> _And how the valiant developers renamed the fields of `ComponentOutput`_
> _To match the OAM spec and avoid confusion in the code_
> _Like the wise Athena changing her form to aid the heroes._

### Walkthrough
*  Rename `StandardWorkload` to `ComponentOutput` and `Traits` to `ComponentOutputsAndTraits` in `ComponentManifest` type to avoid confusion with OAM spec ([link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-350e3ee054dcfc53112a666e6b7b9ce9d1c97c2cc98a1575603dff4de840b23bL29-R32))
  - `prepareArtifactsData` and `SetOAMContract` in `pkg/appfile/appfile.go` ([link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-43788a1ca93b9153bf14f7c6ded757be167657dee1c088fa87bbbca5b345cb8bL269-R272), [link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-43788a1ca93b9153bf14f7c6ded757be167657dee1c088fa87bbbca5b345cb8bL328-R335))
  - `evalWorkloadWithContext` in `pkg/appfile/appfile.go` and `pkg/appfile/appfile_test.go` ([link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-43788a1ca93b9153bf14f7c6ded757be167657dee1c088fa87bbbca5b345cb8bL589-R592), [link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-43788a1ca93b9153bf14f7c6ded757be167657dee1c088fa87bbbca5b345cb8bL604-R604), [link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-1862f643abc85049d047af33bc97640f6b9ce4ff598a8fa599c76abc6bec4543L197-R197), [link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-1862f643abc85049d047af33bc97640f6b9ce4ff598a8fa599c76abc6bec4543L407-R407))
  - `PrepareBeforeApply` and `HandleCheckManageWorkloadTrait` in `pkg/controller/core.oam.dev/v1beta1/application/assemble/assemble.go` ([link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-8a34f1c5a26a8ae25196df356d8b2fa3f6191b20e2c545b885ae594430690faaL55-R55), [link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-8a34f1c5a26a8ae25196df356d8b2fa3f6191b20e2c545b885ae594430690faaL64-R73), [link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-8a34f1c5a26a8ae25196df356d8b2fa3f6191b20e2c545b885ae594430690faaL134-R134))
  - `generateManifest` in `pkg/appfile/dryrun/diff.go` ([link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-07dc4a0f1ce64c21c479fa3e71b28dbd6566b40a1227088fca0866a76b856523L444-R445), [link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-07dc4a0f1ce64c21c479fa3e71b28dbd6566b40a1227088fca0866a76b856523L463-R463))
  - `PrintDryRun` in `pkg/appfile/dryrun/dryrun.go` ([link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-2a394b8f730ba3eee5a25f4522160fa3a067a1131a820303a4597870688b928bL174-R174), [link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-2a394b8f730ba3eee5a25f4522160fa3a067a1131a820303a4597870688b928bL186-R186))
  - `TestGenerateAppRevision` and `TestGenerateAppRevisionWithWorkflow` in `pkg/controller/core.oam.dev/v1beta1/application/application_controller_test.go` ([link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-a4475efde34f88878fdc957c8cc44e508d789cf47e746e01f10b404eb46df7bdL527-R529), [link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-a4475efde34f88878fdc957c8cc44e508d789cf47e746e01f10b404eb46df7bdL750-R750))
  - `TestGenerateComponentFromCUEModule`, `TestEvalWorkloadWithContext`, `TestPrepareArtifactsData`, and `TestGenerateComponentFromCUEModuleWithWorkflow` in `pkg/appfile/appfile_test.go` ([link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-1862f643abc85049d047af33bc97640f6b9ce4ff598a8fa599c76abc6bec4543L197-R197), [link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-1862f643abc85049d047af33bc97640f6b9ce4ff598a8fa599c76abc6bec4543L407-R407), [link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-1862f643abc85049d047af33bc97640f6b9ce4ff598a8fa599c76abc6bec4543L632-R635), [link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-1862f643abc85049d047af33bc97640f6b9ce4ff598a8fa599c76abc6bec4543L736-R738), [link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-1862f643abc85049d047af33bc97640f6b9ce4ff598a8fa599c76abc6bec4543L820-R820))
  - `renderComponentsAndTraits`, `getComponentResources`, and `overrideTraits` in `pkg/controller/core.oam.dev/v1beta1/application/generator.go` ([link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-4170e9b730a11fdd789c7b33a0871e4a67c4e37910815cc262286ac8ec076212L422-R423), [link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-4170e9b730a11fdd789c7b33a0871e4a67c4e37910815cc262286ac8ec076212L489-R489), [link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-4170e9b730a11fdd789c7b33a0871e4a67c4e37910815cc262286ac8ec076212L508-R509), [link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-4170e9b730a11fdd789c7b33a0871e4a67c4e37910815cc262286ac8ec076212L515-R515))
* Rename `overrideTraits` to `redirectTraitToLocalIfNeed` in `pkg/controller/core.oam.dev/v1beta1/application/generator.go` to better reflect its purpose and update the reference in `renderComponentsAndTraits` ([link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-4170e9b730a11fdd789c7b33a0871e4a67c4e37910815cc262286ac8ec076212L422-R423), [link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-4170e9b730a11fdd789c7b33a0871e4a67c4e37910815cc262286ac8ec076212L489-R489))
* Remove `ProduceArtifacts` function and related constants and imports in `pkg/controller/core.oam.dev/v1beta1/application/apply.go` and `pkg/controller/core.oam.dev/v1beta1/application/revision.go` as they are no longer needed after refactoring the application revision logic to use the component manifests directly ([link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-1231f1d18480e1146845f10b71802bdbec731f2ab350d6143baded165e865db6L226-L230), [link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-c21f292d942528312440bd97a929675d5aaff3e5981f800ba492efea10dea032L30), [link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-c21f292d942528312440bd97a929675d5aaff3e5981f800ba492efea10dea032L46), [link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-c21f292d942528312440bd97a929675d5aaff3e5981f800ba492efea10dea032L59-L69), [link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-c21f292d942528312440bd97a929675d5aaff3e5981f800ba492efea10dea032L95-L152))
* Remove `ComputeComponentRevisionHash` function and related import in `pkg/controller/core.oam.dev/v1beta1/application/revision.go` as it is no longer needed after refactoring the application revision logic to use the component revision name and hash labels ([link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-c21f292d942528312440bd97a929675d5aaff3e5981f800ba492efea10dea032L46), [link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-c21f292d942528312440bd97a929675d5aaff3e5981f800ba492efea10dea032L507-L535))
* Remove calls to `ProduceArtifacts` function in various tests in `pkg/controller/core.oam.dev/v1beta1/application/revision_test.go` as the function is no longer needed and removed ([link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-15edf9bc627f1ed3a0159da11bcb8f313c2419a07c07517f577bf6bc90b787acL203), [link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-15edf9bc627f1ed3a0159da11bcb8f313c2419a07c07517f577bf6bc90b787acL241), [link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-15edf9bc627f1ed3a0159da11bcb8f313c2419a07c07517f577bf6bc90b787acL280), [link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-15edf9bc627f1ed3a0159da11bcb8f313c2419a07c07517f577bf6bc90b787acL324), [link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-15edf9bc627f1ed3a0159da11bcb8f313c2419a07c07517f577bf6bc90b787acL368), [link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-15edf9bc627f1ed3a0159da11bcb8f313c2419a07c07517f577bf6bc90b787acL399))
* Update `debugComponents` function in `references/cli/debug.go` to use the new field names of `ComponentOutput` and `ComponentOutputsAndTraits` when creating the maps of components and traits from the component manifests ([link](https://github.com/kubevela/kubevela/pull/6300/files?diff=unified&w=0#diff-ae8e34bba4cfc3f84e9a91d152f2040677c10e6b407fe2ebeca25ebebfb0620fL178-R179))

Fixes #

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [x] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Review by wangyikewxgm — APPROVED** [review]

**Review by wonderflow — COMMENTED** [review]
this is not a refactor, it's a deprecation with several API changes.

**Comment by chivalryq** [comment]
> this is not a refactor, it's a deprecation with several API changes.

Yes, I've chanegd the title.

**Review by Somefive — APPROVED** [review]

**Comment by wonderflow** [comment]
@chivalryq It's still not clear, you'd better make a clarification about which features are deprecated.

**Comment by chivalryq** [comment]
ping @wonderflow

**Pull request merged**
