### PR TITLE
Fix: missing return when token is null

### PR DESCRIPTION
**Pull request by zhiyuone**
Signed-off-by: Zhiyu Wang <cloudsky.newbis@gmail.com>

### Description of your changes

Fixes #

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Review by barnettZQG — APPROVED** [review]
LGTM

**Comment by wonderflow** [comment]
@zhiyuone please help cherry-pick

**Comment by zhiyuone** [comment]
@wonderflow how? 1.4 not need this fix, and i don't know why 1.5 fails.

**Comment by wonderflow** [comment]
1. make your local branch align with the release-1.5
2. checkout a new branch from release-1.5
3. cherry-pick the commit
```
git cherry-pick f7d3fbaeca253be88c0782aead4b8ee76f6c608c
```
4. send a pull request to the release-1.5 branch

**Comment by wonderflow** [comment]
everything goes the same except you're making a pull request to the `release-1.5` branch.

**Pull request merged**
