### PR TITLE
Feat: add affinity trait to merge node and pod affinity

### LINKED ISSUE #3972: [Feature] Add trait definition to support pod affinity
**Is your feature request related to a problem? Please describe.**

add trait definition to support pod affinity.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by ZhongsJie96**
Signed-off-by: ZhongsJie <zhongsjie@cmbchina.com>

### Description of your changes

Fixes #3972 

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Review by fourierr — COMMENTED** [review]
Why is pod-affinity and pod-anti-affinity not in a trait?

**Review by wonderflow — COMMENTED** [review]
let's create a new trait  `affinity`, merge them with https://github.com/kubevela/kubevela/blob/master/vela-templates/definitions/internal/trait/node-affinity.cue into the new one and deprecate the olds.

**Comment by ZhongsJie96** [comment]
> let's create a new trait `affinity`, merge them with https://github.com/kubevela/kubevela/blob/master/vela-templates/definitions/internal/trait/node-affinity.cue into the new one and deprecate the olds.

ok

**Review by wonderflow — APPROVED** [review]
LGTM, please also update the docs: https://kubevela.io/docs/end-user/traits/references

**Comment by ZhongsJie96** [comment]
> LGTM, please also update the docs: https://kubevela.io/docs/end-user/traits/references

OK, I'll update it

**Pull request merged**
