### PR TITLE
added a vscode extension to rub vela vet in the background

### LINKED ISSUE #5366: [Feature] IDE Plugins
**Is your feature request related to a problem? Please describe.**

With more and more developers start writing KubeVela (OAM) application YAML file and CUE-based X-Definitions, it is increasingly important to provide some tools to help user make correct configurations. IDE plugin is one way to reach that. We can make VSCode/Jetbrains plugins for formatting and previewing the written applications.

**Describe the solution you'd like**

The plugin is expected to be able to:
1. Connect to the remote Kubernetes APIServer (KubeVela Control Plane) in the background and recognize the X-Definitions (ComponentDefinitions, TraitDefinitions, PolicyDefinitions, WorkflowStepDefinitions).
2. Highlight the type of components, traits, policies & workflowsteps in the application configuration.
3. Preview the rendering result (dryrun) of the components & traits.
4. Compare the difference between the current application configuration and the corresponding one on the remote cluster.
5. Preview the selected clusters by the topology policy.
6. For ComponentDefinition & TraitDefinition, provide validation for the CUE input and preview for the rendering result.

**Describe alternatives you've considered**

An alternative choice is to make some standalone development tools like desktop apps. It can be developed with cross-platform build tools like electron/dart.

**Additional context**

Feel free to discuss what this tool should be look like below. :)

### PR DESCRIPTION
**Pull request by swastik959**
### Summary
📝🛠️🚀

This pull request adds a new extension for VS Code that validates the syntax and semantics of KubeVela definitions using the `vela def vet` command. The pull request includes the configuration, implementation, documentation, and testing files for the extension. The files follow the VS Code extension development guidelines and best practices.

> _`extension.js` runs_
> _vela def vet command_
> _logs output, errors_

### Walkthrough
*  Add a VS Code extension for validating KubeVela definitions using the `vela def vet` command ([link](https://github.com/kubevela/kubevela/pull/6304/files?diff=unified&w=0#diff-3fb2c1880b706dc83cc51a9e4849935f6a364b23e611d7701d5a5ba11d01bbbfL1-R52), [link](https://github.com/kubevela/kubevela/pull/6304/files?diff=unified&w=0#diff-68b27b4ec51d3370ddba6b19861442817027079ebc3ef2491d58cc6632bb1e2dR1-R43))
*  Configure the extension's metadata, dependencies, scripts, and contributions in `package.json` ([link](https://github.com/kubevela/kubevela/pull/6304/files?diff=unified&w=0#diff-68b27b4ec51d3370ddba6b19861442817027079ebc3ef2491d58cc6632bb1e2dR1-R43))
*  Provide a brief description, features, requirements, settings, issues, and release notes of the extension in `README.md` ([link](https://github.com/kubevela/kubevela/pull/6304/files?diff=unified&w=0#diff-e48280075b9da927c93ea914c35eacfb07f037dc283ca6cd678b808c3ed91e3bR1-R65))
*  Document the notable changes to the extension in each release in `CHANGELOG.md` ([link](https://github.com/kubevela/kubevela/pull/6304/files?diff=unified&w=0#diff-b87846fb48b39278cf062d065175aa49bd6b5c19dd1f5d5caca5f55717f6ce2cL1-R8))
*  Configure the ESLint tool for linting the JavaScript code of the extension in `.eslintrc.json` ([link](https://github.com/kubevela/kubevela/pull/6304/files?diff=unified&w=0#diff-848a7db196017bb0c1630416efc04adbbdd14812a677a5304bb6391db48c1c0fR1-R25))
*  Configure the JavaScript language service for the extension in `jsconfig.json` ([link](https://github.com/kubevela/kubevela/pull/6304/files?diff=unified&w=0#diff-92569c15719219af19fc82095648b19898820b183b4283a7c84a02a3fe2ea4c6R1-R13))
*  Exclude some files and folders from the version control in `.gitignore` ([link](https://github.com/kubevela/kubevela/pull/6304/files?diff=unified&w=0#diff-37a7517a48b86ab5147126c5ed09b83c63f71f6ed24649f82557013d7dd1d384R1-R3))
*  Exclude some files and folders from the extension package in `.vscodeignore` ([link](https://github.com/kubevela/kubevela/pull/6304/files?diff=unified&w=0#diff-310db54e7d55e546670c78b728327b5a26ed2906dba357027e9e69e9cffdce7aR1-R9))
*  Provide a quick start guide for developing the extension using VS Code in `vsc-extension-quickstart.md` ([link](https://github.com/kubevela/kubevela/pull/6304/files?diff=unified&w=0#diff-8852dab7de359655f2649be2a3fe3198fe13eb4f7cef53e1f51be9abd050ab9fR1-R41))
*  Run the integration tests for the extension using the `@vscode/test-electron` module in `runTest.js` ([link](https://github.com/kubevela/kubevela/pull/6304/files?diff=unified&w=0#diff-26f7e48df9c1f156225f8900fbbae06909fd55e6a7bc503282c205c84d4f8bbdR1-R23))
*  Run the test suite for the extension using the `mocha` module in `index.js` ([link](https://github.com/kubevela/kubevela/pull/6304/files?diff=unified&w=0#diff-5b37801c1d6f6278417ddf942cd4b984bb977ac35ab2094faf39ce1b1846c6b3R1-R42))
*  Provide a sample test for the extension using the `assert` module in `extension.test.js` ([link](https://github.com/kubevela/kubevela/pull/6304/files?diff=unified&w=0#diff-671bdacbf54c72dbdc99aefd836f5a04261abf88bbf517ec16e556c1cdcef06cR1-R15))

Fixes #5366

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Comment by Somefive** [comment]
Shall we move this contribution here ->  https://github.com/kubevela-contrib/vscode-plugin?

**Comment by swastik959** [comment]
@Somefive sure

**Comment by Somefive** [comment]
> @Somefive I am unable to fork the repo or push the commits

Try it again now?

**Review by FogDong — COMMENTED** [review]
Any preview image to help review this?

**Comment by Somefive** [comment]
FYI, the PR is merged to https://github.com/kubevela-contrib/vscode-plugin

**Comment by chivalryq** [comment]
Since the extension goes to kubevela-contrib/vscode-plugin. I'll close this PR.

**Pull request closed without merging**
