### PR TITLE
Fix: remove cluster field from pod view in vela top and optimize some ui

### LINKED ISSUE #5229: Incorrect cluster field in vela top pod view
**Describe the bug**

When I compare managed resources view and pod view in vela top, I found the `Cluster` field is correct in managed resources view, but not in pod. view.

**To Reproduce**

**Expected behavior**

The `Cluster` field in pod view is correct.

**Screenshots**

image
type "Enter" ⬇️
image

**KubeVela Version**

CLI version v1.6.4

**Cluster information**

**Additional context**

Related PR: #5228

### PR DESCRIPTION
**Pull request by Hanmengnan**
### Description of your changes

Fixes #5229

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Review by chivalryq — COMMENTED** [review]
Just remove "cluster" field is OK, but can we pass the cluster info from the "managed resource" panel?

**Comment by Hanmengnan** [comment]
> Just remove "cluster" field is OK, but can we pass the cluster info from the "managed resource" panel?

Can we guarantee the cluster of pod is the same as the cluster of managed resource the pod belonging to?

**Comment by chivalryq** [comment]
> Can we guarantee the cluster of pod is the same as the cluster of managed resource the pod belonging to?

If the pod is in a different cluster as managed resource it belongs to, then the managed resource have the capability to dispatch resources across the clusters. For now I think we have  few use case like that. So it's ok to pass the cluster info.

**Comment by Hanmengnan** [comment]
> > Can we guarantee the cluster of pod is the same as the cluster of managed resource the pod belonging to?
> 
> If the pod is in a different cluster as managed resource it belongs to, then the managed resource has the capability to dispatch resources across the clusters. For now I think we have few use case like that. So it's ok to pass the cluster info.

I got it. I have updated code.

**Review by Somefive — APPROVED** [review]

**Pull request merged**
