### PR TITLE
Fix: get Application status using jsonpath filter expression

### LINKED ISSUE #4922: [Bug] Fail to get vela Application status using jsonpath filter expression
**Describe the bug**

We can't get vela Application status using jsonpath filter expression:
```
$ vela status first-vela-app -ojsonpath='{.status.services[?(@.name=="express-server")].healthy}'
Error: unexpected path string, expected a 'name1.name2' or '.name1.name2' or '{name1.name2}' or '{.name1.name2}'
```

But kubectl can do it successfully:
```
$ kubectl -n prod get applications.core.oam.dev first-vela-app -ojsonpath='{.status.services[?(@.name=="express-server")].healthy}'
true
```

**To Reproduce**

1. Create an environment and deploy the application:
```
vela env init prod --namespace prod
vela up -f https://kubevela.net/example/applications/first-app.yaml
```
2. Get vela Application status using jsonpath filter expression:
```
vela status first-vela-app -ojsonpath='{.status.services[?(@.name=="express-server")].healthy}'
```

**Expected behavior**

**Screenshots**

**KubeVela Version**

```
CLI Version: v1.5.8
Core Version: 1.5.8
GitRevision: git-1b7f9aa
GolangVersion: go1.17.13
```

**Cluster information**

**Additional context**

### PR DESCRIPTION
**Pull request by Young-Zen**
### Description of your changes

Fixes #4922

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Review by charlie0129 — APPROVED** [review]
Good job

**Review by wonderflow — COMMENTED** [review]
the refactor LGTM, but I don't see you've fixed the issue refered.

**Comment by wonderflow** [comment]
image

**Comment by Young-Zen** [comment]
> the refactor LGTM, but I don't see you've fixed the issue refered.

The jsonpath filter expression has '=' operator, ```strings.Split(format, "=")``` can't return correct result.

**Comment by Young-Zen** [comment]
> image

Follow your steps, I don't see my fix commit on the branch. Please checkout the correct branch to verify:

image

**Review by wonderflow — APPROVED** [review]
Thanks! Verified, you're right!

**Pull request merged**
