### PR TITLE
Fix: vela status will always get external ip first

### PR DESCRIPTION
**Pull request by chivalryq**
Signed-off-by: Qiaozp <qiaozhongpei.qzp@alibaba-inc.com>

### Description of your changes

`vela status` sometimes print internal IP even if there are external IP for nodes in cluster.
This also have an impact when deploy add-on VelaUX and influence the first-time installation experience.

Fix this by always printing the node's external IP if there are any.

image

Fixes #

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Comment by wonderflow** [comment]
What it works like in ACK？

**Review by barnettZQG — APPROVED** [review]
Great!

**Comment by chivalryq** [comment]
> What it works like in ACK？

@wonderflow  

Now: If first node returned from APIServer have external IP, then return it. Else return this node's internal IP.

After fix:
If there are node with external IP, return the external IP.
If there aren't any, return the first node's internal IP.

In short, this PR make the result more predictable instead of random.

**Pull request merged**
