### PR TITLE
Feat: add verify image repo and list repo tags

### LINKED ISSUE #5088: [Feature] helm repository and image registry add connection verification
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by nuclearwu**
Signed-off-by: wuzhongjian wuzhongjian_yewu@cmss.chinamobile.com

### Description of your changes
add verify image repository and list repository tags function

Fixes #5088 

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Comment by chivalryq** [comment]
I think maybe you should move this PR to VelaUX repo now. See https://github.com/kubevela/kubevela/issues/5487

**Comment by Somefive** [comment]
Apiserver is separated. I think this PR should be moved to https://github.com/kubevela/velaux ?

**Comment by nuclearwu** [comment]
> #5088

ok, have done. please review https://github.com/kubevela/velaux/pull/697

**Comment by wonderflow** [comment]
Thanks @nuclearwu , let's discuss in https://github.com/kubevela/velaux/pull/697 , closing this one

**Pull request closed without merging**
