### PR TITLE
Fix: delete context when patch outputs in trait

### LINKED ISSUE #1851: [Feature] Add support for a trait to patch to any outputs defined before it and not just the output defined by the corresponding component.
**Is your feature request related to a problem? Please describe.**
Currently, traits can patch the workload of the corresponding components only. It is not possible for traits to patch workloads of other traits. This tends to make a trait overly complex when its targeting a fairly complex resource. For e.g. in Istio, a `DestinationRule` is responsible for several related activities like loadbalancing and circuit breaking. However, I would like to expose these as two separate traits. So now I'm in a scenario where a two traits are attempting to work on a single resource which isn't the one described by the corresponding component.

**Describe the solution you'd like**

There should be a field in a CUE part of the trait which indicated which resource is it trying to patch. So a trait can patch the resource defined by the component or any other `outputs` which were defined before it.

**Describe alternatives you've considered**

The only way to solve this right now is to make a separate component for `DestinationRule` all together and attach traits to that instead which doesn't really sound like a good idea.

**Additional context**

### PR DESCRIPTION
**Pull request by FogDong**
Signed-off-by: FogDong <dongtianxin.tx@alibaba-inc.com>

### Description of your changes

Fixes #1851

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### Special notes for your reviewer

/cc @wonderflow

### CODE REVIEW

**Review by wonderflow — APPROVED** [review]
please make sure it won't break any existing use case

**Comment by oiar** [comment]
> 

No effect.

**Comment by oiar** [comment]
> ping @[oiar](https://github.com/oiar), Will this changes affect the patch trait that we use?

No effect.

**Comment by FogDong** [comment]
> Details

It may affect the users who're using `context: outputs: resource` to patch traits in trait definition, but those users are also affected by this bug: the context is overridden.

**Comment by wonderflow** [comment]
> > please make sure it won't break any existing use case
> 
> It may affect the users who're using `context: outputs: resource` to patch traits in trait definition, but those users are also affected by this bug: the context is overridden.

Can you make some clarification about this bug fix and change? I think users will refer to this PR in release not.

**Comment by wonderflow** [comment]
I'll leave this feature in v1.4 and not backport to 1.3. Because it may cause some incompatible.

**Comment by FogDong** [comment]
Though this PR fixes the override context problem raised by #1704 , still, if we want to patch outputs and output at the same time, we'll patch outputs into the output.
We may need to change the code here to avoid it:
1. We can delete the `outputs` part in `patch` when patching to workload. But if we do so, users can not patch the outputs in the workload struct.
2. Or we can delete the original code and add some new field like `patchTrait` to patch traits.

/cc @wonderflow @leejanee @fourierr

**Comment by wonderflow** [comment]
@FogDong Please give some examples

**Comment by FogDong** [comment]
> @FogDong Please give some examples

For example, if we patch trait and workload at the same time in trait, the definition will like:

```yaml
  patch: {
      outputs: {
        service: {
          spec: {
            // +patchKey=port
            // +patchStrategy=retainKeys
            ports: [{
              port: 2333
              targetPort: 2333
              name: "test"
            }]
          }
        }
      }
      spec: template: spec: {
          containers: [{
              name: context.name
              // +patchKey=configMapRef.name,secretRef.name
              // +patchStrategy=retainKeys
              envFrom: [
                  {
                    configMapRef: {
                      name: parameter.cmname
                    }
                  },
                  {
                    secretRef: {
                      name: parameter.sename
                    }
                  }
              ]
          }]
      }
  }
```

After patching, the workload will like:

```yaml
// original workload struct
...

outputs: {
....
}
```

We can delete the `outputs` part when trying to patch the worload, but it'll make `outputs` our built-in field in the workload and users can not use them.

We can also change it to:

```yaml
patch: {
// patch to workload
}

patchTraits: {
// patch to traits
}
```

**Comment by wonderflow** [comment]
Yes, use a separate keyword can make the things easier:

```
patch: {
// patch to workload
}

patchOutputs: {
// patch to traits or outputs from workload
}
```

**Review by leejanee — APPROVED** [review]
LGTM

**Comment by fourierr** [comment]
lgtm

**Pull request merged**
