### PR TITLE
Fix: fix the annotation for APIService

### PR DESCRIPTION
**Pull request by zzxwill**
Make the annatation for cert-manger be the same as the new version
secret

Signed-off-by: Zheng Xi Zhou <zhengxi.zzx@alibaba-inc.com>

### Description of your changes

Fixes #

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Review by Somefive — APPROVED** [review]

**Review by wonderflow — CHANGES_REQUESTED** [review]
please confirm, the cert manage is using v2? What's the error message？

**Comment by Somefive** [comment]
> please confirm, the cert manage is using v2? What's the error message？

In https://github.com/kubevela/kubevela/pull/4072/files, the secret for cluster-gateway is changed to v2. However, the cert-manager is still injecting ca from the old secret. This PR fixes it.

**Comment by wonderflow** [comment]
> > please confirm, the cert manage is using v2? What's the error message？
> 
> In https://github.com/kubevela/kubevela/pull/4072/files, the secret for cluster-gateway is changed to v2. However, the cert-manager is still injecting ca from the old secret. This PR fixes it.

So if users enable cert-manager, this issue will occur?

**Comment by Somefive** [comment]
> > > please confirm, the cert manage is using v2? What's the error message？
> > 
> > 
> > In https://github.com/kubevela/kubevela/pull/4072/files, the secret for cluster-gateway is changed to v2. However, the cert-manager is still injecting ca from the old secret. This PR fixes it.
> 
> So if users enable cert-manager, this issue will occur?

Yes.

**Review by wonderflow — APPROVED** [review]
thanks

**Pull request merged**
