### PR TITLE
Feat: support field selector filter for 'vela ls'

### PR DESCRIPTION
**Pull request by nuclearwu**
Signed-off-by: wuzhongjian <wuzhongjian_yewu@cmss.chinamobile.com>

### Description of your changes
support field selector filter for 'vela ls'

Fixes #

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Comment by Somefive** [comment]
LGTM. A small question for this PR. Could `kubectl get app -l key=value` satisfy your need?

**Comment by nuclearwu** [comment]
> LGTM. A small question for this PR. Could `kubectl get app --field-selector key=value` satisfy your need?

no, `kubectl get app --field-selector key=value`only supports a limited number of field queries per type. As we know, the field selector is still not working well with custom resources, https://github.com/kubernetes/kubernetes/issues/51046.

**Comment by Somefive** [comment]
@nuclearwu I see.
Another two things to mention:
1. I find that there is a jsonpath library imported. In KubeVela we already have some json related library. Is this new library import necessary? Or is there any more authoritative/recommended implementation library?
2. I suggest moving functions like `FilteredList` to `pkg/utils/k8s.go` and rename to more clear names like `FilterObjectsByFieldSelector`.

**Comment by nuclearwu** [comment]
> @nuclearwu I see. Another two things to mention:
> 
> 1. I find that there is a jsonpath library imported. In KubeVela we already have some json related library. Is this new library import necessary? Or is there any more authoritative/recommended implementation library?
> 2. I suggest moving functions like `FilteredList` to `pkg/utils/k8s.go` and rename to more clear names like `FilterObjectsByFieldSelector`.

done, please review.

**Comment by Somefive** [comment]
@nuclearwu Looks great. Could you add some simple test in k8s_test.go as well? (Or move some test there)

**Comment by nuclearwu** [comment]
> @nuclearwu Looks great. Could you add some simple test in k8s_test.go as well? (Or move some test there)

@Somefive done, please review

**Review by Somefive — APPROVED** [review]

**Pull request merged**
