### PR TITLE
Feat: align resource selector across policies

### LINKED ISSUE #4594: ApplyOnce ResourceSelector ambiguous and not aligned with other ResourceSelector
**Describe the bug**

The implementation for FindStrategy in apply-once policy is confusing. 

https://github.com/kubevela/kubevela/blob/436ff916b65fcf3e57e7043904343e9db6bbcec1/apis/core.oam.dev/v1alpha1/applyonce_types.go#L62

The major problem is that it misuses `componentNames` and `resourceNames`.

The minor problem is that this selector is not aligned with selector in other policies (garbage-collect & shared-resource).

https://github.com/kubevela/kubevela/blob/436ff916b65fcf3e57e7043904343e9db6bbcec1/apis/core.oam.dev/v1alpha1/garbagecollect_types.go#L74

I plan to refactor this part of code. Is there any special case that might break existing usage outside test cases?
/cc @fourierr 

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

### PR DESCRIPTION
**Pull request by Somefive**
Signed-off-by: Somefive <yd219913@alibaba-inc.com>

### Description of your changes

Fixes #4594

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### Special notes for your reviewer

/cc @fourierr

### CODE REVIEW

**Comment by fourierr** [comment]
It covers my usage completely. How about exposing an operator to provide the ability of chossing "and" , "or" for user.

**Comment by Somefive** [comment]
> It covers my usage completely. How about exposing an operator to provide the ability of chossing "and" , "or" for user.

I actually think for a while, but this exposure might be a bit complex for user. The AND case is more reasonable I think, as you proposed in apply-once previously. The OR case on the other hand, can be implemented through configuring multiple rules, which is a bit more complex but available. By far, I haven't seen cases use OR actually. We can leave this for future implementation if we encountered lots of such usage.

**Comment by fourierr** [comment]
> > It covers my usage completely. How about exposing an operator to provide the ability of chossing "and" , "or" for user.
> 
> I actually think for a while, but this exposure might be a bit complex for user. The AND case is more reasonable I think, as you proposed in apply-once previously. The OR case on the other hand, can be implemented through configuring multiple rules, which is a bit more complex but available. By far, I haven't seen cases use OR actually. We can leave this for future implementation if we encountered lots of such usage.

👌

**Review by fourierr — APPROVED** [review]
lgtm

**Review by barnettZQG — APPROVED** [review]
LGTM

**Review by FogDong — APPROVED** [review]

**Pull request merged**
