### PR TITLE
Feat: created Terraform Provider for GCP,EC and VSPHERE

### PR DESCRIPTION
**Pull request by emanuelr93**
Open in substution of https://github.com/oam-dev/kubevela/pull/2458

Adding support for:

AWS
GCP
VSPHERE
EC

### CODE REVIEW

**Review by zzxwill — APPROVED** [review]
Great job! And welcome back:)

Please also update the official site https://kubevela.io. You can refer to this PR https://github.com/oam-dev/kubevela.io/pull/348.

**Comment by emanuelr93** [comment]
> Great job! And welcome back:)
> 
> Please also update the official site https://kubevela.io. You can refer to this PR [oam-dev/kubevela.io#348](https://github.com/oam-dev/kubevela.io/pull/348).

Do I create a dedicated PR to this, or do you prefer that I use this PR directly?

**Comment by zzxwill** [comment]
Please run 'make reviewable' to include all changes

**Comment by emanuelr93** [comment]
> Please run 'make reviewable' to include all changes

Done. But i don't kwow why check-diff fail again.

**Comment by chivalryq** [comment]
Maybe something goes wrong in your `make reviewable`(which is strange). But you can simply delete `foo_deepcopy.go` in your commit and push again.

**Comment by wonderflow** [comment]
@emanuelr93 Hi， are you still working on that?

**Comment by wonderflow** [comment]
closing as the addon has been migrated to https://github.com/kubevela/catalog. 

You're welcome to send a pull request there.

**Pull request closed without merging**
