### PR TITLE
Fix:  loading definitions if lack in the revision when calculate dispatch stage of trait.

### PR DESCRIPTION
**Pull request by wangyikewxgm**
### Description of your changes

When we add a trait to a component with an inline policy, the trait's definition isn't stored in the application revision. As a result, to determine if the traitDefinition's stage is predispatch or postdispatch, we must retrieve it from the cluster.

This pr is a fix for https://github.com/kubevela/kubevela/pull/5416

Fixes #

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Review by wonderflow — COMMENTED** [review]
can you describe why do we need this PR?

**Comment by wangyikewxgm** [comment]
> can you describe why do we need this PR?

When we add a trait to a component with an inline policy, the trait's definition isn't stored in the application revision. As a result, to determine if the traitDefinition's stage is predispatch or postdispatch, we must retrieve it from the cluster

**Review by Somefive — APPROVED** [review]
LGTM

**Comment by FogDong** [comment]
> /cc @FogDong I think this PR is a temporary fix as it possibly means when introducing new trait via inlinePolicy we would get the definition multiple times. It would be better if the design of our new TemplateLoader could use cache to optimize this. :)

Actually I think we shouldn't get trait from the cluster for inline policy. Instead, the trait that used in the policy should also be stored in the revision.

**Review by wonderflow — CHANGES_REQUESTED** [review]
Is there a way to achieve it in one step? Let's not use temporary solutions. @Somefive @FogDong @wangyikewxgm

**Comment by Somefive** [comment]
No, it is associated the mechanism of loading definitions so it is out of the scope of workflowstep itself.

**Review by FogDong — APPROVED** [review]

**Comment by Somefive** [comment]
> Is there a way to achieve it in one step? Let's not use temporary solutions. @Somefive @FogDong @wangyikewxgm

It is a temporary solution but by far we do not have better solutions.

**Review by wonderflow — APPROVED** [review]

**Pull request merged**
