### PR TITLE
Fix: fix the vela show error when format the output markdown

### LINKED ISSUE #6259: vela show --format markdown fails with ComponentDefinition
**Describe the bug**
with kubevela 1.9.5 the following error happens with ComponentDefinition:
```
vela show .webservice.cue --format markdown
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x48 pc=0x106b7aedc]

goroutine 1 [running]:
github.com/oam-dev/kubevela/references/docgen.(*MarkdownReference).GenerateMarkdownForCap(_, {_, _}, {{0x140010d8420, 0xa}, {0x106f1fa20, 0x13}, {0x140012be000, 0x36b0}, {0x0, ...}, ...}, ...)
	github.com/oam-dev/kubevela/references/docgen/markdown.go:174 +0x2fc
github.com/oam-dev/kubevela/references/docgen.(*MarkdownReference).CreateMarkdown(0x14000523ad0, {0x10800d0d8, 0x140000780c8}, {0x140008ce3c0, 0x1, 0x1}, {0x16b56f206, 0x4}, 0x0, 0x0?)
	github.com/oam-dev/kubevela/references/docgen/markdown.go:86 +0x1d4
github.com/oam-dev/kubevela/references/docgen.(*MarkdownReference).GenerateReferenceDocs(0x14000523ad0, {0x10800d0d8, 0x140000780c8}, {0x1400106c480, 0x0, 0x14000773490, {0x0, 0x0}, 0x14001018640, 0x0}, ...)
	github.com/oam-dev/kubevela/references/docgen/markdown.go:70 +0xe0
github.com/oam-dev/kubevela/references/cli.ShowReferenceMarkdown({0x10800d0d8, 0x140000780c8}, {0x0, 0x0, 0x14000773490, {0x0, 0x0}, 0x0, 0x0}, {{0x107fe6b00, ...}, ...}, ...)
	github.com/oam-dev/kubevela/references/cli/show.go:473 +0x124
github.com/oam-dev/kubevela/references/cli.NewCapabilityShowCommand.func1(0x14000331800?, {0x140010d51d0?, 0x5?, 0x5?})
	github.com/oam-dev/kubevela/references/cli/show.go:119 +0x334
github.com/spf13/cobra.(*Command).execute(0x14000331800, {0x140010d5180, 0x5, 0x5})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x1400029ef00)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(0x107fe6b00?)
	github.com/spf13/cobra@v1.7.0/command.go:992 +0x1c
main.main()
	github.com/oam-dev/kubevela/references/cmd/cli/main.go:41 +0x174
```

This was not happening with kubevela 1.8 and it's working with traitDefinitions....

**To Reproduce**

Run vela show --format markdown with a ComponentDefinition as webservice

**Expected behavior**

Generate the markdown

**KubeVela Version**

1.9.5

**Cluster information**

Kubernetes 1.26

### PR DESCRIPTION
**Pull request by Mcduller**
### Description of your changes
when generate markdowm doc, we need client to get the base resource kind, or we will get panic.

### Summary
🐛📝🚀

Fix `vela show` command to support cluster capabilities. Use Kubernetes client from common arguments to fetch capability definition from the cluster if needed.

> _`vela show` command_
> _needs Kubernetes client_
> _to fetch capabilities_

### Walkthrough
* Enable reference parser to fetch capability definition from cluster if location is not specified ([link](https://github.com/kubevela/kubevela/pull/6356/files?diff=unified&w=0#diff-fda687850fdcee4f75d3d3e9cadcabe43bb8c554e2ec5b678d420e87d2f5cc08L467-R477))

Fixes #6259

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Comment by chivalryq** [comment]
What's the issue if client is not provided? Please complement the PR description.

**Comment by Mcduller** [comment]
> What's the issue if client is not provided? Please complement the PR description.
need the client's restMapper to get base resource kind of the cue template. if the client is not provide, it will panic

**Review by chivalryq — APPROVED** [review]
LGTM, could you post a successful command screenshot?

**Comment by Mcduller** [comment]
> LGTM, could you post a successful command screenshot?

image
@chivalryq this is a screenshot in debug mode

**Pull request merged**
