### PR TITLE
Fix(CUE): fix namespaces field missing in the requiredDuringSchedulingIgnoredDuringExecution at affinity trait

### LINKED ISSUE #6554: The affinity Trait is missing the namespaces field.
**Describe the bug**
```
The affinity Trait is missing the namespaces field.
       if parameter.podAffinity.required != _|_ {
        requiredDuringSchedulingIgnoredDuringExecution: [
         for k in parameter.podAffinity.required {
          if k.labelSelector != _|_ {
        	  labelSelector: k.labelSelector
          }
          if k.namespace != _|_ {
        	  namespace: k.namespace
          }
          ...
          **Here missing namespaces field**
          topologyKey: k.topologyKey
          if k.namespaceSelector != _|_ {
        	  namespaceSelector: k.namespaceSelector
          }
         }]
       }

```
**KubeVela Version**
main

### PR DESCRIPTION
**Pull request by fyp711**
### Description of your changes

copilot:all

Fixes #6554

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [x] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

Write a required affinity configuration, then configure the namespaces field

### CODE REVIEW

**Comment by fyp711** [comment]
@FogDong Why `make reviewable` want to delete this commit context ?
image

**Comment by fyp711** [comment]
Hi @FogDong , Could you help me ? Thanks!

**Comment by fyp711** [comment]
> Hi @FogDong Why `make reviewable` want to delete this commit context ? image

**Comment by fyp711** [comment]
> Hi @FogDong Why `make reviewable` want to delete this commit context ? image

@FogDong Could you help me to explain this issue?

**Review by FogDong — COMMENTED** [review]
Please make changes in cue file instead of yaml: https://github.com/kubevela/kubevela/blob/master/vela-templates/definitions/internal/trait/affinity.cue
After the modification, run `make reviewable`, it will automatically generate the yaml files based on the cue files.

**Comment by fyp711** [comment]
> Please make changes in cue file instead of yaml: https://github.com/kubevela/kubevela/blob/master/vela-templates/definitions/internal/trait/affinity.cue After the modification, run `make reviewable`, it will automatically generate the yaml files based on the cue files.

@FogDong  I get it. It dawned on me. Thank you !

**Comment by fyp711** [comment]
Hi, there some work flow failed, could you help rerun it? Thanks.

**Comment by fyp711** [comment]
Hi, @FogDong Could you review again?

**Review by FogDong — COMMENTED** [review]
Please rebase from master.

**Comment by fyp711** [comment]
@FogDong see https://github.com/kubevela/kubevela/pull/6567 , and then close this pull request. Thanks!

**Pull request closed without merging**
