### PR TITLE
Feat: vela auth gen-kubeconfig

### PR DESCRIPTION
**Pull request by Somefive**
Signed-off-by: Somefive <yd219913@alibaba-inc.com>


### Description of your changes

<!--

Briefly describe what this pull request does. We love pull requests that resolve an open KubeVela issue. If yours does, you
can uncomment the below line to indicate which issue your PR fixes, for example
"Fixes #500":

-->

`vela auth gen-kubeconfig` generate kubeconfig for users with given User/Groups or ServiceAccount.

For User/Groups, the command will generate a new private key, create a CertificateSigningRequest, approve itself and generate kubeconfig with the signed X.509 certificate.

For ServiceAccount, the command will find the serviceaccount secret and generate kubeconfig with the token inside the secret.

Example usage:

```                                                                                                                                                     
  # Generate a kubeconfig with provided user
  vela auth gen-kubeconfig --user new-user                                                                                                                    
                                                                                                                                                              
  # Generate a kubeconfig with provided user and group                                                                                                        
  vela auth gen-kubeconfig --user new-user --group kubevela:developer                                                                                         
   
  # Generate a kubeconfig with provided user and groups
  vela auth gen-kubeconfig --user new-user --group kubevela:developer --group my-org:my-team
                             
  # Generate a kubeconfig with provided serviceaccount
  vela auth gen-kubeconfig --serviceaccount default -n demo
```

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.

### How has this code been tested

<!--
Before reviewers can be confident in the correctness of this pull request, it
needs to tested and shown to be correct. Briefly describe the testing that has
already been done or which is planned for this change.
-->


### Special notes for your reviewer

<!--

Be sure to direct your reviewers'
attention to anything that needs special consideration.

-->

Other commands that will be developed following this PR.
- `vela auth list-privileges --user <User> --group <Group> --serviceaccount <ServiceAccount> --namespace <Namespace> --cluster <Cluster>`

### CODE REVIEW

**Comment by wonderflow** [comment]
vela create is not good enough to be occupied in this usage

**Comment by wonderflow** [comment]
vela auth？

**Comment by Somefive** [comment]
> vela auth？

`vela auth kubeconfig` is confusing. `vela auth create kubeconfig` is a bit long. Besides, this also affects other Role/RoleBinding/ClusterRole/ClusterRoleBinding commands. I was thinking using `vela auth` but ends finding it is relatively redundant.

**Comment by Somefive** [comment]
> vela create is not good enough to be occupied in this usage

Actually, in `kubectl`, there are a bunch of resources that uses the subcommand from `kubectl create`, like `kubectl create deployment` or `kubectl create serviceaccount`. However, those are all resources and `kubeconfig` here is a bit different. So `vela create` might be a bit improper.

**Comment by barnettZQG** [comment]
@Somefive Can you provide a scenario, of what commands users should use?

**Comment by Somefive** [comment]
> @Somefive Can you provide a scenario, of what commands users should use?

For example, if you are the admin, you want to give demo namespace's permission to a user named Alice, and Alice want to access the demo namespace with vela-cli, like create an application or check application running status.

The first step admin needs to do, is to give her a kubeconfig file. This file  cannot be a copy of the admin's kubeconfig, since that will cause Alice to have very large permissions, like deleting other people's namespace. With this PR, admin can run *vela create kubeconfig --user=alice* first, and give Alice the generated kubeconfig. Then the admin can run *vela create rolebinding -cluster-role=edit --user=alice --cluster=local,cluster1,cluster2 --namespace=demo*, this will give Alice the privileges to manipulate resources in demo namespace in three clusters.

**Comment by Somefive** [comment]
> vela auth？

@wonderflow `vela auth create kubeconfig` although a bit long but clear enough? I think this one is ok to me.

**Review by barnettZQG — APPROVED** [review]

**Comment by wonderflow** [comment]
> > vela auth？
> 
> @wonderflow `vela auth create kubeconfig` although a bit long but clear enough? I think this one is ok to me.

What about `vela auth create --kubeconfig` ? There can be other type of authorization

**Comment by Somefive** [comment]
> > > vela auth？
> > 
> > 
> > @wonderflow `vela auth create kubeconfig` although a bit long but clear enough? I think this one is ok to me.
> 
> What about `vela auth create --kubeconfig` ? There can be other type of authorization.
> 
> ```
> vela auth gen --kubeconfig
> ```

How about `vela auth gen-kubeconfig`? Otherwise we would need to have `vela auth gen --kubeconfig --user --group` seems a bit weird?

**Comment by wonderflow** [comment]
```
vela auth gen-kubeconfig
```

works for me

**Comment by zzxwill** [comment]
How will the generated kubeconfig be used? By joining as a cluster with limited permissions?

**Comment by Somefive** [comment]
> How will the generated kubeconfig be used? By joining as a cluster with limited permissions?

No, the kubeconfig generation here is not related with joining clusters. It works for the control plane. For example, you are the admin of the control plane, you want to give a developer the permission to run applications in `demo` namespace. This command can create a kubeconfig for that developer, since giving the admin's kubeconfig to that developer will give the developer overlarge permissions.

**Review by zzxwill — APPROVED** [review]

**Pull request merged**
