### PR TITLE
Fix: removes `default` parameter name for terraform provider

### LINKED ISSUE #5427: [Feature Request] Double check on config update
**Describe the bug**

When I create the second config using terraform-alibaba template, vela CLI override and update the default provider silently. This causes all the cloud resources in my cluster to re-build. 

This is dangerous and we can add a double check when overriding happens.

**To Reproduce**

1. vela config create foo -t terraform-alibaba ALICLOUD_REGION=cn-hangzhou ALICLOUD_ACCESS_KEY=$ALICLOUD_ACCESS_KEY ALICLOUD_SECRET_KEY=$ALICLOUD_SECRET_KEY
2. vela config create bar -t terraform-alibaba ALICLOUD_REGION=cn-hangzhou ALICLOUD_ACCESS_KEY=$ALICLOUD_ACCESS_KEY ALICLOUD_SECRET_KEY=$ALICLOUD_SECRET_KEY
3. Check the Provider. The provider `default` is updated with newer config.

**Expected behavior**

In CLI, the config creation should be provide prompts if the command will update the 
**Screenshots**

In CLI: Don't allow update config output (e.g. Provider) to be updated silently. It could provide a double check prompt to ask user if this is intended.

### PR DESCRIPTION
**Pull request by afzalbin64**
### Description of your changes

Fixes #5427 

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [x] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Review by chivalryq — COMMENTED** [review]
The user prompt should only show when the config will be override. User shouldn't be asked twice when creating a new config.

**Comment by chivalryq** [comment]
After offline talk with @afzalbin64 . #5427 should be fixed by remove default provider name ("default") in config templates. This PR can be closed. 
See: https://github.com/kubevela/catalog/pull/638

**Comment by chivalryq** [comment]
Please fix the test.

**Comment by afzalbin64** [comment]
cc @chivalryq @wonderflow

**Review by chivalryq — APPROVED** [review]

**Review by Somefive — APPROVED** [review]

**Review by FogDong — APPROVED** [review]

**Review by FogDong — COMMENTED** [review]
Should this be backported to 1.7?

**Pull request merged**
