### PR TITLE
Fix: the array type cannot be converted to interface type

### LINKED ISSUE #5564: [Bug]Failed to query policy details generated by application
**Describe the bug**

Failed to query policy details generated by application, as shown in the picture.
image
image

**To Reproduce**

1、vela addon enable dbtype=mongodb dbURL=mongodb://
2、use velaux to create application

image
image
image
image

**Expected behavior**

**Screenshots**

**KubeVela Version**
1.7.4

**Cluster information**

1.21.5

**Additional context**

### PR DESCRIPTION
**Pull request by nuclearwu**
### Description of your changes

Fixes #5564 

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Comment by nuclearwu** [comment]
@barnettZQG

**Review by FogDong — COMMENTED** [review]
Can you add some tests?

**Comment by nuclearwu** [comment]
> Can you add some tests?

ok, done, please review again @FogDong

**Comment by nuclearwu** [comment]
@barnettZQG @FogDong

**Review by barnettZQG — APPROVED** [review]
LGTM

**Comment by nuclearwu** [comment]
> LGTM

Is it necessary to backport 1.6.x ？ @barnettZQG

**Pull request merged**
